version: '3'

services:

  front:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - "80:8880"
      - "443:8443"
    volumes:
      - ./server-confs:/server-confs
      - ./distfront:/www
      - ./certificates:/etc/letsencrypt
    environment:
      - SERVER_NAME=doodle.diverse-team.fr pad.diverse-team.fr phpmyadmin.divers-team.fr
      - SAVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      
  back:
    image: barais/doodleback-with-quarkus
    ports:
     - "8080:8080"
    volumes:
     - ./backconfig:/work/config
    deploy:
     replicas: 6
     placement:
      max_replicas_per_node: 1
     restart_policy:
      condition: on-failure
    
  mydb:
    image: mysql
    restart: always
    ports: 
      - "3306:3386"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
      - MY_SQL_ALLOW_EMPTY_PASSWORD=true

  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9081"
    volumes:
      - ./etherpadkey/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
