version: '3.8'

services:

  front:
    image: tlcfront
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./server-confs:/server-confs:ro
      - ./distfront:/www
      - ./certificates:/etc/letsencrypt
    environment:
      - SERVER_NAME=doodle.diverse-team.fr etherpad.diverse-team.fr
      - SAVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      #No si local, yes sur VM
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      #
      - USE_LIMIT_REQ=no
      - HTTP2=no
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'
      
  back:
    image: tlcback
    ports:
     - "8080:8080"
    volumes:
     - ./backconfig:/work/config
    deploy:
      restart_policy:
        condition: on-failure
    
  mydb:
    image: mysql
    restart: always
    ports: 
      - "3306:3386"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
      - MY_SQL_ALLOW_EMPTY_PASSWORD=true

  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9081"
    volumes:
      - ./etherpadkey/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
